import { Among, SnowballStemmer } from '@nlpjs-neo/core';
import TokenizerEn from './tokenizer-en.js';

/**
 * This class was automatically generated by a Snowball to JSX compiler
 * It implements the stemming algorithm defined by a snowball script.
 */
class StemmerEn extends SnowballStemmer {
  declare B_Y_found: boolean;
  declare static a_0: Among<StemmerEn>[];
  declare static a_10: Among<StemmerEn>[];
  declare static a_1: Among<StemmerEn>[];
  declare static a_2: Among<StemmerEn>[];
  declare static a_3: Among<StemmerEn>[];
  declare static a_4: Among<StemmerEn>[];
  declare static a_5: Among<StemmerEn>[];
  declare static a_6: Among<StemmerEn>[];
  declare static a_7: Among<StemmerEn>[];
  declare static a_8: Among<StemmerEn>[];
  declare static a_9: Among<StemmerEn>[];
  declare static g_v: number[];
  declare static g_v_WXY: number[];
  declare static g_valid_LI: number[];
  declare static methodObject: StemmerEn;

  constructor(container?) {
    super(container);
    this.name = 'stemmer-en';
    this.B_Y_found = false;
    this.I_p2 = 0;
    this.I_p1 = 0;
  }

  getTokenizer() {
    if (!this.tokenizer) {
      this.tokenizer =
        this.container.get(`tokenizer-${this.name.slice(-2)}`) ||
        new TokenizerEn();
      if (this.tokenizer.constructor.name === 'Tokenizer') {
        this.tokenizer = new TokenizerEn();
      }
    }
    return this.tokenizer;
  }

  r_prelude() {
    // unset Y_found
    this.B_Y_found = false;
    // do
    const v_1 = this.cursor;
    lab0: {
      this.bra = this.cursor;
      if (!this.eq_s("'")) {
        break lab0;
      }
      this.ket = this.cursor;
      if (!this.slice_del()) {
        return false;
      }
    }
    this.cursor = v_1;
    // do
    const v_2 = this.cursor;
    lab1: {
      this.bra = this.cursor;
      if (!this.eq_s('y')) {
        break lab1;
      }
      this.ket = this.cursor;
      if (!this.slice_from('Y')) {
        return false;
      }
      // set Y_found
      this.B_Y_found = true;
    }
    this.cursor = v_2;
    // do
    const v_3 = this.cursor;
    {
      // repeat
      replab3: for (;;) {
        const v_4 = this.cursor;
        lab4: {
          // goto
          golab5: for (;;) {
            const v_5 = this.cursor;
            lab6: {
              if (!this.in_grouping(StemmerEn.g_v, 97, 121)) {
                break lab6;
              }
              this.bra = this.cursor;
              if (!this.eq_s('y')) {
                break lab6;
              }
              this.ket = this.cursor;
              this.cursor = v_5;
              break golab5;
            }
            this.cursor = v_5;
            if (this.cursor >= this.limit) {
              break lab4;
            }
            this.cursor++;
          }
          if (!this.slice_from('Y')) {
            return false;
          }
          // set Y_found
          this.B_Y_found = true;
          continue replab3;
        }
        this.cursor = v_4;
        break;
      }
    }
    this.cursor = v_3;
    return true;
  }

  r_mark_regions() {
    this.I_p1 = this.limit;
    this.I_p2 = this.limit;
    // do
    const v_1 = this.cursor;
    lab0: {
      // or
      lab1: {
        const v_2 = this.cursor;
        lab2: {
          if (this.find_among(StemmerEn.a_0, 3) === 0) {
            break lab2;
          }
          break lab1;
        }
        this.cursor = v_2;
        // gopast
        if (!this.gopast_in_grouping(StemmerEn.g_v, 97, 121)) {
          break lab0;
        }
        // gopast
        if (!this.gopast_out_grouping(StemmerEn.g_v, 97, 121)) {
          break lab0;
        }
      }
      this.I_p1 = this.cursor;
      // gopast
      if (!this.gopast_in_grouping(StemmerEn.g_v, 97, 121)) {
        break lab0;
      }
      // gopast
      if (!this.gopast_out_grouping(StemmerEn.g_v, 97, 121)) {
        break lab0;
      }
      this.I_p2 = this.cursor;
    }
    this.cursor = v_1;
    return true;
  }

  r_shortv() {
    // or
    lab0: {
      const v_1 = this.limit - this.cursor;
      lab1: {
        if (!this.out_grouping_b(StemmerEn.g_v_WXY, 89, 121)) {
          break lab1;
        }
        if (!this.in_grouping_b(StemmerEn.g_v, 97, 121)) {
          break lab1;
        }
        if (!this.out_grouping_b(StemmerEn.g_v, 97, 121)) {
          break lab1;
        }
        break lab0;
      }
      this.cursor = this.limit - v_1;
      if (!this.out_grouping_b(StemmerEn.g_v, 97, 121)) {
        return false;
      }
      if (!this.in_grouping_b(StemmerEn.g_v, 97, 121)) {
        return false;
      }
      // atlimit
      if (this.cursor > this.limit_backward) {
        return false;
      }
    }
    return true;
  }

  r_Step_1a() {
    let among_var;

    // try
    const v_1 = this.limit - this.cursor;
    lab0: {
      this.ket = this.cursor;
      among_var = this.find_among_b(StemmerEn.a_1, 3);
      if (among_var === 0) {
        this.cursor = this.limit - v_1;
        break lab0;
      }
      this.bra = this.cursor;
      switch (among_var) {
        case 0:
          this.cursor = this.limit - v_1;
          break lab0;
        case 1:
          if (!this.slice_del()) {
            return false;
          }
          break;
      }
    }
    this.ket = this.cursor;
    among_var = this.find_among_b(StemmerEn.a_2, 6);
    if (among_var === 0) {
      return false;
    }
    this.bra = this.cursor;
    switch (among_var) {
      case 0:
        return false;
      case 1:
        if (!this.slice_from('ss')) {
          return false;
        }
        break;
      case 2:
        // or
        lab1: {
          const v_2 = this.limit - this.cursor;
          lab2: {
            {
              const c = this.cursor - 2;
              if (this.limit_backward > c || c > this.limit) {
                break lab2;
              }
              this.cursor = c;
            }
            if (!this.slice_from('i')) {
              return false;
            }
            break lab1;
          }
          this.cursor = this.limit - v_2;
          if (!this.slice_from('ie')) {
            return false;
          }
        }
        break;
      case 3:
        if (this.cursor <= this.limit_backward) {
          return false;
        }
        this.cursor--;
        // gopast
        if (!this.gopast_in_grouping_b(StemmerEn.g_v, 97, 121)) {
          return false;
        }
        if (!this.slice_del()) {
          return false;
        }
        break;
    }
    return true;
  }

  r_Step_1b() {
    let v_1;
    let v_3;
    let v_4;
    this.ket = this.cursor;
    let among_var = this.find_among_b(StemmerEn.a_4, 6);
    if (among_var === 0) {
      return false;
    }
    this.bra = this.cursor;
    switch (among_var) {
      case 0:
        return false;
      case 1:
        if (!this.r_R1()) {
          return false;
        }
        if (!this.slice_from('ee')) {
          return false;
        }
        break;
      case 2:
        // test
        v_1 = this.limit - this.cursor;
        // gopast
        if (!this.gopast_in_grouping_b(StemmerEn.g_v, 97, 121)) {
          return false;
        }
        this.cursor = this.limit - v_1;
        if (!this.slice_del()) {
          return false;
        }
        // test
        v_3 = this.limit - this.cursor;
        among_var = this.find_among_b(StemmerEn.a_3, 13);
        if (among_var === 0) {
          return false;
        }
        this.cursor = this.limit - v_3;
        switch (among_var) {
          case 0:
            return false;
          case 1:
            {
              const c = this.cursor;
              this.insert(this.cursor, this.cursor, 'e');
              this.cursor = c;
            }
            break;
          case 2:
            this.ket = this.cursor;
            if (this.cursor <= this.limit_backward) {
              return false;
            }
            this.cursor--;
            this.bra = this.cursor;
            if (!this.slice_del()) {
              return false;
            }
            break;
          case 3:
            // atmark
            if (this.cursor !== this.I_p1) {
              return false;
            }
            // test
            v_4 = this.limit - this.cursor;
            if (!this.r_shortv()) {
              return false;
            }
            this.cursor = this.limit - v_4;
            {
              const c = this.cursor;
              this.insert(this.cursor, this.cursor, 'e');
              this.cursor = c;
            }
            break;
        }
        break;
    }
    return true;
  }

  r_Step_1c() {
    this.ket = this.cursor;
    // or
    lab0: {
      const v_1 = this.limit - this.cursor;
      lab1: {
        if (!this.eq_s_b('y')) {
          break lab1;
        }
        break lab0;
      }
      this.cursor = this.limit - v_1;
      if (!this.eq_s_b('Y')) {
        return false;
      }
    }
    this.bra = this.cursor;
    if (!this.out_grouping_b(StemmerEn.g_v, 97, 121)) {
      return false;
    }
    // not
    {
      const v_2 = this.limit - this.cursor;
      lab2: {
        // atlimit
        if (this.cursor > this.limit_backward) {
          break lab2;
        }
        return false;
      }
      this.cursor = this.limit - v_2;
    }
    if (!this.slice_from('i')) {
      return false;
    }
    return true;
  }

  r_Step_2() {
    this.ket = this.cursor;
    const among_var = this.find_among_b(StemmerEn.a_5, 24);
    if (among_var === 0) {
      return false;
    }
    this.bra = this.cursor;
    if (!this.r_R1()) {
      return false;
    }
    switch (among_var) {
      case 0:
        return false;
      case 1:
        if (!this.slice_from('tion')) {
          return false;
        }
        break;
      case 2:
        if (!this.slice_from('ence')) {
          return false;
        }
        break;
      case 3:
        if (!this.slice_from('ance')) {
          return false;
        }
        break;
      case 4:
        if (!this.slice_from('able')) {
          return false;
        }
        break;
      case 5:
        if (!this.slice_from('ent')) {
          return false;
        }
        break;
      case 6:
        if (!this.slice_from('ize')) {
          return false;
        }
        break;
      case 7:
        if (!this.slice_from('ate')) {
          return false;
        }
        break;
      case 8:
        if (!this.slice_from('al')) {
          return false;
        }
        break;
      case 9:
        if (!this.slice_from('ful')) {
          return false;
        }
        break;
      case 10:
        if (!this.slice_from('ous')) {
          return false;
        }
        break;
      case 11:
        if (!this.slice_from('ive')) {
          return false;
        }
        break;
      case 12:
        if (!this.slice_from('ble')) {
          return false;
        }
        break;
      case 13:
        if (!this.eq_s_b('l')) {
          return false;
        }
        if (!this.slice_from('og')) {
          return false;
        }
        break;
      case 14:
        if (!this.slice_from('ful')) {
          return false;
        }
        break;
      case 15:
        if (!this.slice_from('less')) {
          return false;
        }
        break;
      case 16:
        if (!this.in_grouping_b(StemmerEn.g_valid_LI, 99, 116)) {
          return false;
        }
        if (!this.slice_del()) {
          return false;
        }
        break;
    }
    return true;
  }

  r_Step_3() {
    this.ket = this.cursor;
    const among_var = this.find_among_b(StemmerEn.a_6, 9);
    if (among_var === 0) {
      return false;
    }
    this.bra = this.cursor;
    if (!this.r_R1()) {
      return false;
    }
    switch (among_var) {
      case 0:
        return false;
      case 1:
        if (!this.slice_from('tion')) {
          return false;
        }
        break;
      case 2:
        if (!this.slice_from('ate')) {
          return false;
        }
        break;
      case 3:
        if (!this.slice_from('al')) {
          return false;
        }
        break;
      case 4:
        if (!this.slice_from('ic')) {
          return false;
        }
        break;
      case 5:
        if (!this.slice_del()) {
          return false;
        }
        break;
      case 6:
        if (!this.r_R2()) {
          return false;
        }
        if (!this.slice_del()) {
          return false;
        }
        break;
    }
    return true;
  }

  r_Step_4() {
    this.ket = this.cursor;
    const among_var = this.find_among_b(StemmerEn.a_7, 18);
    if (among_var === 0) {
      return false;
    }
    this.bra = this.cursor;
    if (!this.r_R2()) {
      return false;
    }
    switch (among_var) {
      case 0:
        return false;
      case 1:
        if (!this.slice_del()) {
          return false;
        }
        break;
      case 2:
        // or
        lab0: {
          const v_1 = this.limit - this.cursor;
          lab1: {
            if (!this.eq_s_b('s')) {
              break lab1;
            }
            break lab0;
          }
          this.cursor = this.limit - v_1;
          if (!this.eq_s_b('t')) {
            return false;
          }
        }
        if (!this.slice_del()) {
          return false;
        }
        break;
    }
    return true;
  }

  r_Step_5() {
    this.ket = this.cursor;
    const among_var = this.find_among_b(StemmerEn.a_8, 2);
    if (among_var === 0) {
      return false;
    }
    this.bra = this.cursor;
    switch (among_var) {
      case 0:
        return false;
      case 1:
        // or
        lab0: {
          const v_1 = this.limit - this.cursor;
          lab1: {
            if (!this.r_R2()) {
              break lab1;
            }
            break lab0;
          }
          this.cursor = this.limit - v_1;
          if (!this.r_R1()) {
            return false;
          }
          // not
          {
            const v_2 = this.limit - this.cursor;
            lab2: {
              if (!this.r_shortv()) {
                break lab2;
              }
              return false;
            }
            this.cursor = this.limit - v_2;
          }
        }
        if (!this.slice_del()) {
          return false;
        }
        break;
      case 2:
        if (!this.r_R2()) {
          return false;
        }
        if (!this.eq_s_b('l')) {
          return false;
        }
        if (!this.slice_del()) {
          return false;
        }
        break;
    }
    return true;
  }

  r_exception2() {
    this.ket = this.cursor;
    if (this.find_among_b(StemmerEn.a_9, 8) === 0) {
      return false;
    }
    this.bra = this.cursor;
    // atlimit
    if (this.cursor > this.limit_backward) {
      return false;
    }
    return true;
  }

  r_exception1() {
    this.bra = this.cursor;
    const among_var = this.find_among(StemmerEn.a_10, 18);
    if (among_var === 0) {
      return false;
    }
    this.ket = this.cursor;
    // atlimit
    if (this.cursor < this.limit) {
      return false;
    }
    switch (among_var) {
      case 0:
        return false;
      case 1:
        if (!this.slice_from('ski')) {
          return false;
        }
        break;
      case 2:
        if (!this.slice_from('sky')) {
          return false;
        }
        break;
      case 3:
        if (!this.slice_from('die')) {
          return false;
        }
        break;
      case 4:
        if (!this.slice_from('lie')) {
          return false;
        }
        break;
      case 5:
        if (!this.slice_from('tie')) {
          return false;
        }
        break;
      case 6:
        if (!this.slice_from('idl')) {
          return false;
        }
        break;
      case 7:
        if (!this.slice_from('gentl')) {
          return false;
        }
        break;
      case 8:
        if (!this.slice_from('ugli')) {
          return false;
        }
        break;
      case 9:
        if (!this.slice_from('earli')) {
          return false;
        }
        break;
      case 10:
        if (!this.slice_from('onli')) {
          return false;
        }
        break;
      case 11:
        if (!this.slice_from('singl')) {
          return false;
        }
        break;
    }
    return true;
  }

  r_postlude() {
    // Boolean test Y_found
    if (!this.B_Y_found) {
      return false;
    }
    // repeat
    replab0: for (;;) {
      const v_1 = this.cursor;
      lab1: {
        // goto
        golab2: for (;;) {
          const v_2 = this.cursor;
          lab3: {
            this.bra = this.cursor;
            if (!this.eq_s('Y')) {
              break lab3;
            }
            this.ket = this.cursor;
            this.cursor = v_2;
            break golab2;
          }
          this.cursor = v_2;
          if (this.cursor >= this.limit) {
            break lab1;
          }
          this.cursor++;
        }
        if (!this.slice_from('y')) {
          return false;
        }
        continue replab0;
      }
      this.cursor = v_1;
      break;
    }
    return true;
  }

  innerStem() {
    // or
    lab0: {
      const v_1 = this.cursor;
      lab1: {
        if (!this.r_exception1()) {
          break lab1;
        }
        break lab0;
      }
      this.cursor = v_1;
      lab2: {
        // not
        {
          const v_2 = this.cursor;
          lab3: {
            {
              const c = this.cursor + 3;
              if (c < 0 || c > this.limit) {
                break lab3;
              }
              this.cursor = c;
            }
            break lab2;
          }
          this.cursor = v_2;
        }
        break lab0;
      }
      this.cursor = v_1;
      // do
      const v_3 = this.cursor;
      lab4: {
        if (!this.r_prelude()) {
          break lab4;
        }
      }
      this.cursor = v_3;
      // do
      const v_4 = this.cursor;
      lab5: {
        if (!this.r_mark_regions()) {
          break lab5;
        }
      }
      this.cursor = v_4;
      // backwards
      this.limit_backward = this.cursor;
      this.cursor = this.limit;
      // do
      const v_5 = this.limit - this.cursor;
      lab6: {
        if (!this.r_Step_1a()) {
          break lab6;
        }
      }
      this.cursor = this.limit - v_5;
      // or
      lab7: {
        const v_6 = this.limit - this.cursor;
        lab8: {
          if (!this.r_exception2()) {
            break lab8;
          }
          break lab7;
        }
        this.cursor = this.limit - v_6;
        // do
        const v_7 = this.limit - this.cursor;
        lab9: {
          if (!this.r_Step_1b()) {
            break lab9;
          }
        }
        this.cursor = this.limit - v_7;
        // do
        const v_8 = this.limit - this.cursor;
        lab10: {
          if (!this.r_Step_1c()) {
            break lab10;
          }
        }
        this.cursor = this.limit - v_8;
        // do
        const v_9 = this.limit - this.cursor;
        lab11: {
          if (!this.r_Step_2()) {
            break lab11;
          }
        }
        this.cursor = this.limit - v_9;
        // do
        const v_10 = this.limit - this.cursor;
        lab12: {
          if (!this.r_Step_3()) {
            break lab12;
          }
        }
        this.cursor = this.limit - v_10;
        // do
        const v_11 = this.limit - this.cursor;
        lab13: {
          if (!this.r_Step_4()) {
            break lab13;
          }
        }
        this.cursor = this.limit - v_11;
        // do
        const v_12 = this.limit - this.cursor;
        lab14: {
          if (!this.r_Step_5()) {
            break lab14;
          }
        }
        this.cursor = this.limit - v_12;
      }
      this.cursor = this.limit_backward; // do
      const v_13 = this.cursor;
      lab15: {
        if (!this.r_postlude()) {
          break lab15;
        }
      }
      this.cursor = v_13;
    }
    return true;
  }
}

StemmerEn.methodObject = new StemmerEn();

StemmerEn.a_0 = [
  new Among('arsen', -1, -1),
  new Among('commun', -1, -1),
  new Among('gener', -1, -1),
];

StemmerEn.a_1 = [
  new Among("'", -1, 1),
  new Among("'s'", 0, 1),
  new Among("'s", -1, 1),
];

StemmerEn.a_2 = [
  new Among('ied', -1, 2),
  new Among('s', -1, 3),
  new Among('ies', 1, 2),
  new Among('sses', 1, 1),
  new Among('ss', 1, -1),
  new Among('us', 1, -1),
];

StemmerEn.a_3 = [
  new Among('', -1, 3),
  new Among('bb', 0, 2),
  new Among('dd', 0, 2),
  new Among('ff', 0, 2),
  new Among('gg', 0, 2),
  new Among('bl', 0, 1),
  new Among('mm', 0, 2),
  new Among('nn', 0, 2),
  new Among('pp', 0, 2),
  new Among('rr', 0, 2),
  new Among('at', 0, 1),
  new Among('tt', 0, 2),
  new Among('iz', 0, 1),
];

StemmerEn.a_4 = [
  new Among('ed', -1, 2),
  new Among('eed', 0, 1),
  new Among('ing', -1, 2),
  new Among('edly', -1, 2),
  new Among('eedly', 3, 1),
  new Among('ingly', -1, 2),
];

StemmerEn.a_5 = [
  new Among('anci', -1, 3),
  new Among('enci', -1, 2),
  new Among('ogi', -1, 13),
  new Among('li', -1, 16),
  new Among('bli', 3, 12),
  new Among('abli', 4, 4),
  new Among('alli', 3, 8),
  new Among('fulli', 3, 14),
  new Among('lessli', 3, 15),
  new Among('ousli', 3, 10),
  new Among('entli', 3, 5),
  new Among('aliti', -1, 8),
  new Among('biliti', -1, 12),
  new Among('iviti', -1, 11),
  new Among('tional', -1, 1),
  new Among('ational', 14, 7),
  new Among('alism', -1, 8),
  new Among('ation', -1, 7),
  new Among('ization', 17, 6),
  new Among('izer', -1, 6),
  new Among('ator', -1, 7),
  new Among('iveness', -1, 11),
  new Among('fulness', -1, 9),
  new Among('ousness', -1, 10),
];

StemmerEn.a_6 = [
  new Among('icate', -1, 4),
  new Among('ative', -1, 6),
  new Among('alize', -1, 3),
  new Among('iciti', -1, 4),
  new Among('ical', -1, 4),
  new Among('tional', -1, 1),
  new Among('ational', 5, 2),
  new Among('ful', -1, 5),
  new Among('ness', -1, 5),
];

StemmerEn.a_7 = [
  new Among('ic', -1, 1),
  new Among('ance', -1, 1),
  new Among('ence', -1, 1),
  new Among('able', -1, 1),
  new Among('ible', -1, 1),
  new Among('ate', -1, 1),
  new Among('ive', -1, 1),
  new Among('ize', -1, 1),
  new Among('iti', -1, 1),
  new Among('al', -1, 1),
  new Among('ism', -1, 1),
  new Among('ion', -1, 2),
  new Among('er', -1, 1),
  new Among('ous', -1, 1),
  new Among('ant', -1, 1),
  new Among('ent', -1, 1),
  new Among('ment', 15, 1),
  new Among('ement', 16, 1),
];

StemmerEn.a_8 = [new Among('e', -1, 1), new Among('l', -1, 2)];

StemmerEn.a_9 = [
  new Among('succeed', -1, -1),
  new Among('proceed', -1, -1),
  new Among('exceed', -1, -1),
  new Among('canning', -1, -1),
  new Among('inning', -1, -1),
  new Among('earring', -1, -1),
  new Among('herring', -1, -1),
  new Among('outing', -1, -1),
];

StemmerEn.a_10 = [
  new Among('andes', -1, -1),
  new Among('atlas', -1, -1),
  new Among('bias', -1, -1),
  new Among('cosmos', -1, -1),
  new Among('dying', -1, 3),
  new Among('early', -1, 9),
  new Among('gently', -1, 7),
  new Among('howe', -1, -1),
  new Among('idly', -1, 6),
  new Among('lying', -1, 4),
  new Among('news', -1, -1),
  new Among('only', -1, 10),
  new Among('singly', -1, 11),
  new Among('skies', -1, 2),
  new Among('skis', -1, 1),
  new Among('sky', -1, -1),
  new Among('tying', -1, 5),
  new Among('ugly', -1, 8),
];

StemmerEn.g_v = [17, 65, 16, 1];

StemmerEn.g_v_WXY = [1, 17, 65, 208, 1];

StemmerEn.g_valid_LI = [55, 141, 2];

export default StemmerEn;
