import { Among, BaseStemmer } from '@nlpjs-neo/core';
import type { ContainerHolder } from '@nlpjs-neo/core';

/**
 * This class was automatically generated by a Snowball to JSX compiler
 * It implements the stemming algorithm defined by a snowball script.
 */

class StemmerNo extends BaseStemmer {
  declare I_p1: number;
  declare I_x: number;

  constructor(container?: ContainerHolder) {
    super(container);
    this.name = 'stemmer-no';
    this.I_x = 0;
    this.I_p1 = 0;
  }

  copy_from(other: StemmerNo) {
    this.I_x = other.I_x;
    this.I_p1 = other.I_p1;
    super.copy_from(other);
  }

  r_mark_regions(): boolean {
    this.I_p1 = this.limit;
    // test
    const v_1 = this.cursor;
    {
      const c = this.cursor + 3;
      if (c < 0 || c > this.limit) {
        return false;
      }
      this.cursor = c;
    }
    this.I_x = this.cursor;
    this.cursor = v_1;
    // goto
    if (!this.goto_in_grouping(StemmerNo.g_v, 97, 248)) {
      return false;
    }
    // gopast
    if (!this.gopast_out_grouping(StemmerNo.g_v, 97, 248)) {
      return false;
    }
    this.I_p1 = this.cursor;
    // try
    lab4: {
      if (!(this.I_p1 < this.I_x)) {
        break lab4;
      }
      this.I_p1 = this.I_x;
    }
    return true;
  }

  r_main_suffix(): boolean {
    const v_1 = this.limit - this.cursor;
    if (this.cursor < this.I_p1) {
      return false;
    }
    this.cursor = this.I_p1;
    const v_2 = this.limit_backward;
    this.limit_backward = this.cursor;
    this.cursor = this.limit - v_1;
    this.ket = this.cursor;
    const among_var = this.find_among_b(StemmerNo.a_0);
    if (among_var === 0) {
      this.limit_backward = v_2;
      return false;
    }
    this.bra = this.cursor;
    this.limit_backward = v_2;
    switch (among_var) {
      case 1:
        if (!this.slice_del()) {
          return false;
        }
        break;
      case 2:
        // or
        lab0: {
          const v_3 = this.limit - this.cursor;
          lab1: {
            if (!this.in_grouping_b(StemmerNo.g_s_ending, 98, 122)) {
              break lab1;
            }
            break lab0;
          }
          this.cursor = this.limit - v_3;
          if (!this.eq_s_b('k')) {
            return false;
          }
          if (!this.out_grouping_b(StemmerNo.g_v, 97, 248)) {
            return false;
          }
        }
        if (!this.slice_del()) {
          return false;
        }
        break;
      case 3:
        if (!this.slice_from('er')) {
          return false;
        }
        break;
    }
    return true;
  }

  r_consonant_pair(): boolean {
    // test
    const v_1 = this.limit - this.cursor;
    const v_2 = this.limit - this.cursor;
    if (this.cursor < this.I_p1) {
      return false;
    }
    this.cursor = this.I_p1;
    const v_3 = this.limit_backward;
    this.limit_backward = this.cursor;
    this.cursor = this.limit - v_2;
    this.ket = this.cursor;
    if (this.find_among_b(StemmerNo.a_1) === 0) {
      this.limit_backward = v_3;
      return false;
    }
    this.bra = this.cursor;
    this.limit_backward = v_3;
    this.cursor = this.limit - v_1;
    if (this.cursor <= this.limit_backward) {
      return false;
    }
    this.cursor--;
    this.bra = this.cursor;
    if (!this.slice_del()) {
      return false;
    }
    return true;
  }

  r_other_suffix(): boolean {
    const v_1 = this.limit - this.cursor;
    if (this.cursor < this.I_p1) {
      return false;
    }
    this.cursor = this.I_p1;
    const v_2 = this.limit_backward;
    this.limit_backward = this.cursor;
    this.cursor = this.limit - v_1;
    this.ket = this.cursor;
    const among_var = this.find_among_b(StemmerNo.a_2);
    if (among_var === 0) {
      this.limit_backward = v_2;
      return false;
    }
    this.bra = this.cursor;
    this.limit_backward = v_2;
    switch (among_var) {
      case 1:
        if (!this.slice_del()) {
          return false;
        }
        break;
    }
    return true;
  }

  innerStem(): boolean {
    // do
    const v_1 = this.cursor;
    this.r_mark_regions();
    this.cursor = v_1;
    // backwards
    this.limit_backward = this.cursor;
    this.cursor = this.limit;
    // do
    const v_2 = this.limit - this.cursor;
    this.r_main_suffix();
    this.cursor = this.limit - v_2;
    // do
    const v_3 = this.limit - this.cursor;
    this.r_consonant_pair();
    this.cursor = this.limit - v_3;
    // do
    const v_4 = this.limit - this.cursor;
    this.r_other_suffix();
    this.cursor = this.limit - v_4;
    this.cursor = this.limit_backward;
    return true;
  }

  static a_0: Among<StemmerNo>[] = [
    new Among('a', -1, 1),
    new Among('e', -1, 1),
    new Among('ede', 1, 1),
    new Among('ande', 1, 1),
    new Among('ende', 1, 1),
    new Among('ane', 1, 1),
    new Among('ene', 1, 1),
    new Among('hetene', 6, 1),
    new Among('erte', 1, 3),
    new Among('en', -1, 1),
    new Among('heten', 9, 1),
    new Among('ar', -1, 1),
    new Among('er', -1, 1),
    new Among('heter', 12, 1),
    new Among('s', -1, 2),
    new Among('as', 14, 1),
    new Among('es', 14, 1),
    new Among('edes', 16, 1),
    new Among('endes', 16, 1),
    new Among('enes', 16, 1),
    new Among('hetenes', 19, 1),
    new Among('ens', 14, 1),
    new Among('hetens', 21, 1),
    new Among('ers', 14, 1),
    new Among('ets', 14, 1),
    new Among('et', -1, 1),
    new Among('het', 25, 1),
    new Among('ert', -1, 3),
    new Among('ast', -1, 1),
  ];

  static a_1: Among<StemmerNo>[] = [
    new Among('dt', -1, -1),
    new Among('vt', -1, -1),
  ];

  static a_2: Among<StemmerNo>[] = [
    new Among('leg', -1, 1),
    new Among('eleg', 0, 1),
    new Among('ig', -1, 1),
    new Among('eig', 2, 1),
    new Among('lig', 2, 1),
    new Among('elig', 4, 1),
    new Among('els', -1, 1),
    new Among('lov', -1, 1),
    new Among('elov', 7, 1),
    new Among('slov', 7, 1),
    new Among('hetslov', 9, 1),
  ];

  static g_v: number[] = [
    17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 0, 128,
  ];

  static g_s_ending: number[] = [119, 125, 149, 1];
}

export default StemmerNo;
